# Generated by Django 3.2.6 on 2021-11-10 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myplaylist',
            name='album_id',
            field=models.CharField(default='', max_length=10000000),
        ),
    ]
